// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBurlKJspq6rRMx2nHo5gvoN4s7MM02Sa4',
    appId: '1:305418702970:web:02e3bd37cdec6bd2cf2bc3',
    messagingSenderId: '305418702970',
    projectId: 'task-manajemen-apps',
    authDomain: 'task-manajemen-apps.firebaseapp.com',
    storageBucket: 'task-manajemen-apps.appspot.com',
    measurementId: 'G-JZS4R1Z342',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAdAEG48STEtifuadH-qmXB3iFlI4FYT4',
    appId: '1:305418702970:android:e415279b4104c581cf2bc3',
    messagingSenderId: '305418702970',
    projectId: 'task-manajemen-apps',
    storageBucket: 'task-manajemen-apps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaSQt8vBbNtRsZtuN2D2QkPQDEOOSQW5Q',
    appId: '1:305418702970:ios:9856fb8248a48e7ecf2bc3',
    messagingSenderId: '305418702970',
    projectId: 'task-manajemen-apps',
    storageBucket: 'task-manajemen-apps.appspot.com',
    androidClientId: '305418702970-de6hn4306ofvg8pqnr7tr4g13k3ill7t.apps.googleusercontent.com',
    iosClientId: '305418702970-egab22vbv1d90hto0us6qu5trqllk60b.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaSQt8vBbNtRsZtuN2D2QkPQDEOOSQW5Q',
    appId: '1:305418702970:ios:9856fb8248a48e7ecf2bc3',
    messagingSenderId: '305418702970',
    projectId: 'task-manajemen-apps',
    storageBucket: 'task-manajemen-apps.appspot.com',
    androidClientId: '305418702970-de6hn4306ofvg8pqnr7tr4g13k3ill7t.apps.googleusercontent.com',
    iosClientId: '305418702970-egab22vbv1d90hto0us6qu5trqllk60b.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp',
  );
}
